server:
  port: 9093

eureka:
  instance:
    hostname: localhost
    port: 9091
  client:
    registerWithEureka: true
    fetchRegistry: false
    serviceUrl:
      defaultZone: http://${eureka.instance.hostname}:${eureka.instance.port}/eureka/
  server:
    wait-time-in-ms-when-sync-empty: 3000
    
security:
    oauth2:
        client:            
            scope: password
    
spring:
    datasource:
        #data: classpath:/sql/data.sql
        driver-class-name: org.postgresql.Driver        
        platform: postgres
        #schema: classpath:/sql/schema.sql
        url: jdbc:postgresql://localhost:5432/oauth?verifyServerCertificate=false&useSSL=false&requireSSL=false
        username: postgres
        password: 'postgres'
    jpa:
        database-platform: org.hibernate.dialect.PostgreSQL94Dialect
        generate-ddl: true
        #generate-ddl: false
        hibernate:        
            ddl-auto: create-drop
            #ddl-auto: none
        show-sql: true
        properties:
            hibernate:               
                jdbc:
                    lob:
                        non_contextual_creation: true